### ISSUE TITLE
ACFG Block Feature Order

### ISSUE THREAD

**Issue by cjchristopher** [ryderling/MalGraph#2]
Hi - you state in the paper that the features you use for the block features are:
No. of:
call, transfer, arithmetic, logic, compare, move, termination, date declaration, total instructions, string or integer constants, offspring

However, looking at your sample.jsonl, this is not the order those features are listed in the example, as far as I can see - if they were, the sample is suggesting that no node in either CFG has any offspring at all? 

Could you please provide the correct order for these features, or confirm that the order doesn't matter?

Also, could you please confirm what 'date declaration' is? is it meant to be data declaration? 

I am familiar with the GENIUS code, but their code only harvests 7 numerical features per node, not 11.
Is there any chance you are able to provide in this repo the modified code you used from the GENIUS project?

**Comment by ryderling** [comment]
Thanks for your attention. For your questions:
1. In our paper, the order of node features does not matter.
2. sorry for the typo of `data declaration`,  actually here we want to count the instructions like db, db, dq, etc.
